# Step1 : Import Librarys

In [ ]:
import numpy as np
import math
import matplotlib.pyplot as plt

# Step2 : Get Data

In [ ]:
class1 = [[2, 1], [3, 2], [1, 0]]
class2 = [[-1, -2], [-2, -1], [-1, -1]]
class1 = np.array(class1, dtype=float)
class2 = np.array(class2, dtype=float)
data = [class1, class2]

# Step3 : Calculate Mean Vectors

In [ ]:
mean = []
for class_data in data:
    mean_vector = [0]*len(class_data[0])
    for vector in class_data:
        for index, element in enumerate(vector):
            mean_vector[index] += element
    for index, element in enumerate(mean_vector):
            mean_vector[index] /= len(class_data)
    mean.append(mean_vector)

In [ ]:
mean

[[2.0, 1.0], [-1.3333333333333333, -1.3333333333333333]]

# Step4 : Calculate Scatter Matrixes

In [ ]:
final_scatter_matrix_list = []
for index_class, class_data in enumerate(data):
    scatter_matrix = [[0]*len(class_data[0])] * len(class_data[0])
    scatter_matrix = np.array(scatter_matrix, dtype=float)
    for vector in class_data:
        scatter_vector = [0]*len(class_data[0])
        scatter_vector = np.array(scatter_vector, dtype=float)
        for index, element in enumerate(vector):
            scatter_vector[index] = element - mean[index_class][index]

        scatter_vector = scatter_vector.reshape(-1, 1)
        scatter_matrix += scatter_vector @ scatter_vector.T
    final_scatter_matrix_list.append(scatter_matrix)

final_scatter_matrix = [[0]*len(class_data[0])] * len(class_data[0])
for matrix in final_scatter_matrix_list:
    final_scatter_matrix += matrix

In [ ]:
final_scatter_matrix

array([[2.66666667, 1.66666667],
       [1.66666667, 2.66666667]])

# Step5 : Calculate Optimal Projection Vector

In [ ]:
mean = np.array(mean, dtype=float)
diffrence_matrix = mean[0] - mean[1]
associated = np.linalg.inv(final_scatter_matrix) @ diffrence_matrix

In [ ]:
associated

array([1.15384615, 0.15384615])

# Step6 : Normalize Optimal Projection Vector

In [ ]:
norm = np.linalg.norm(associated)
projection_vector = associated / norm

In [ ]:
projection_vector

array([0.9912279 , 0.13216372])

# Step7 : Reduce Dimension with LDA

In [ ]:
transform_class1 = []
for row in class1:
    transform_class1.append(np.dot(row, projection_vector))

transform_class2 = []
for row in class2:
    transform_class2.append(np.dot(row, projection_vector))

In [ ]:
transform_class1

[2.1146195214562873, 3.23801114222994, 0.9912279006826347]

In [ ]:
transform_class2

[-1.2555553408646705, -2.1146195214562873, -1.1233916207736527]